spring:
  datasource:
    url: jdbc:mysql://localhost:3306/revworkforce_employees?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: Abhishek
    password: Abhi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

app:
  jwt:
    secret: Abhidata2024SecretKeyForJWTTokenGenerationMustBe256BitsLong

logging:
  level:
    com.revworkforce.employee: DEBUG
